server:
  port: 8060

eureka:
  client:
    instance:
      prefer-ip-address: true
    client:
      register-with-eureka: false
    serviceUrl:
      defaultZone: http://server-registry:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: main-service
          #          uri: lb://main-service
          uri: http://main-service:8061
          predicates:
            - Path=/api/main/**
          filters:
            - AuthenticationFilter
        - id: runtime-service
          uri: http://realtime-service:8062
          #          uri: lb://realtime-service
          predicates:
            - Path=/api/realtime/**
          filters:
            - AuthenticationFilter



