server:
  port: 8061
  servlet:
    context-path: /api/main

management:
  security:
    enabled: false
spring:
  application:
    name: main-service
  data:
    elasticsearch:
      cluster-nodes: 34.87.190.66:9200
  cache:
    jcache:
      config: classpath:ehcache.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://securetoken.google.com/artistrysocialnetwork
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
  datasource:
    url: jdbc:mysql://34.87.190.66:3306/snap_connectDb
    useSSL: true
    username: root
    password: RHUowB1w__*e3MBZGAf0
#    url: jdbc:mysql://socialdb-artistrysocialnetwork.a.aivencloud.com:13508/projectsem4
#    useSSL: true
#    username: avnadmin
#    password: AVNS_KXx-W0Q-CbV9LAAh4HF
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: huy.tran9510@gmail.com
    password: omupuqnffjlqjcac
    properties.mail:
      smtp:
        auth: true
        starttls:
          enable: true
    protocol: smtp
    default-encoding: UTF-8
    test-connection: false

eureka:
  client:
    service-url:
      defaultZone: http://server-registry:8761/eureka

env:
  elasticsearch_pass: "RHUowB1w__*e3MBZGAf0"
  elasticsearch_host_and_port: "34.87.190.66:9200"
  secret_token: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  firebaseConfig: |
    {
      "type": "service_account",
      "project_id": "artistrysocialnetwork",
      "private_key_id": "f02aac57d8c77d4c927042a8e3b775e80cabc742",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCV6oNgkNNzvb5v\ndbzs/9AavLjhC4p7YCzpOuN1xMeOk19IA+5lhVCE084+q4uS8F/MRwxQJei4EL/O\nFWwjdai4fshYGpaxs5H0FRHnNnKgL2DL+ifPkrYgPjO4uZDlciTURY8FbFJCnQUy\nFNP/9Scut2A8ON69najE4LAt0w4ws9ymevtefoK5qx9m9wqIF5TCY7l8/5aQwtMR\n5/rEH9fFt3xJDSU/aDjn/M1MATwgSCIM/Dp9TsCyveHHyfYtirCGm6LfVKP5XKpp\n4cPsvxxiyy1kmYXC6fE4MrCcB7//3l63c1QQskLvQIz95d+isOzCU+K6ciY0J0jq\njpRPOuzXAgMBAAECggEAAn5OBRMjkS88tZndtItkqK0u3f9VJEwrMw3ZrqHBN+vX\nj9kQ4/tdpXfoXD56Kc15qmocGFEpF7afmgvdKpHQZpElP+HhU79K1CZtj8zmBygC\nkiHs+5TTFqIyNgZQFKDbX/RwNoTgsV7vMTALfpxTNIG0RgwkGD9BCVU7WOfDuqec\noegQDP+Z8+/Ie8+S63R+hSGPgeLsW/f+IaaJelkwFh2SHgTGUzjARLysVCGORIig\nHAdzo/KVyJcbKX9jh/viYt2EadXL+bGesdm3Pw4RQCaf5L5OlE1GgFjv0tFWBLlR\ncJlpLNTSDjJp2+6Bbuw0OImOHuGKGibK79IQzuNWAQKBgQDRbxA5/Nru9qU8JG27\nWTW9iALrJm6Hmv3LFSOY4DSlT8xgMaRCwsDB8tjsTuhI1JdA/ixKnLPRvWZwWDAs\nhYUwHo0E3o3WnLbSR43GbD6hc+LDThC4RR69siEqryPbgLQ/NkMN9cZkU0ThavFI\nxpLo8IGSmwfCWTMeNakj+IjxVwKBgQC3P7VzoKnuDrXvkW/FyCZtKIJ56uYFWyXF\nXshYSbFRoEYugdPmtx30foxgkJ5CMDy0wABlcxs7P1lhUtFxftKvM/C5ZjAQpvWb\nMbuKtUWxXrtPdk+nxTneH1SnVV3TGlRcHli5IX+f5Z6my7TbGq0DLQAxBLiaanq4\n46Ie2i8wgQKBgQCqYTROOIrTxQv/tZMfyx+RJUlajFV3NHwr7vKauCucISMfTsNX\nHKE8J5iaBkeqmGjEkwLtYDZZ9z+TPetTDPyhfPk0cOnrImsI/vUz63O4XVKpmKS5\nhGHR6UxaMUl2lWoN0tMSVFQl4igzSpEop4N0xdRjtIPHdFHFzdngTZz62QKBgCV0\n7E4aRSHX9/BkNgijhNdDNIhfL21g2DOj0CfbyFb6/915xCqgu4rCY0dJyE+XNJFt\nvab/BE30AP0XxKACYGZXo5kB/kkpF4MFg2Qy8W/0AS2Y7WdJtS5mEROzK15/P0cl\nHNWat0+jy+4kLW+r4DmJ9UQPxvwpT7SDMxxDVOoBAoGAcO0jseOyGGMNoyIzaTLj\nrFfFMbmS6OJY45VZl4tLRATe20mZYjjSiZsVt8yMKCKtMh/4GeiJZ2Q5In5EETjR\nBGJltJmCuQlbLObv3OClaSIzliLOVWzMXhegv1r8jUOpsS/O56eVosHrF0IEJjtJ\nJ0nE4LOtwI+YKckt5cMDoiU=\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-qczy2@artistrysocialnetwork.iam.gserviceaccount.com",
      "client_id": "118371271166639966787",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-qczy2%40artistrysocialnetwork.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
  images:
    default:
      avatar: "https://firebasestorage.googleapis.com/v0/b/artistrysocialnetwork.appspot.com/o/images%2Fdefault%2Favatar.png?alt=media&token=c2a513bb-f750-4710-a0fb-4e745c8359ac"
      background: "https://firebasestorage.googleapis.com/v0/b/artistrysocialnetwork.appspot.com/o/images%2Fdefault%2Fbackgroud.png?alt=media&token=0492673b-2bac-4859-a48b-40acd4cfc220"
