server:
  port: 8082
  servlet:
    context-path: /api/realtime


spring:
  application:
    name: realtime-service
  cache:
    jcache:
      config: classpath:ehcache.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  data:
    mongodb:
      data:
        mongodb:
          host: mongodb
          port: 27017
          database: snap_connectDb
          username: root
          password: RHUowB1w__*e3MBZGAf0

eureka:
  client:
    service-url:
      defaultZone: http://server-registry:8761/eureka

env:
  CLIENT_URL: http://localhost:3000
  SECRET_KEY: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
