server:
  port: 8082
  servlet:
    context-path: /api/runtime


spring:
  application:
    name: runtime-service

eureka:
  client:
    service-url:
      defaultZone: http://server-registry:8761/eureka
