
spring:
  application:
    name: server-registry
eureka:
  instance:
    hostname: server-registry
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8761
