server:
  port: 8060

eureka:
  client:
    client:
      register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: main-service
            uri: lb://main-service
            predicates:
              - Path=/api/main/**
          - id: runtime-service
            uri: lb://runtime-service
            predicates:
              - Path=/api/runtime/**


