server:
  port: 8081
  servlet:
    context-path: /api/main

spring:
  application:
    name: main-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectsem4
    username: mario
    password: Tiennam1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
