server:
  port: 8080
  servlet:
    context-path: /api/main
management:
  security:
    enabled: false
spring:
  application:
    name: main-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://socialweb.mysql.database.azure.com:3306/projectsem4
    useSSL: true
    username: project
    password: Thuhuy@123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
