server:
  port: 8089
  servlet:
    context-path: /api/realtime


spring:
  application:
    name: realtime-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/post_test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

env:
  CLIENT_URL: http://localhost:3000
