server:
  port: 8081
  servlet:
    context-path: /api/realtime


spring:
  application:
    name: realtime-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
