export enum UserRole{
    ROLE_USER ="ROLE_USER",
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_PROVIDER="ROLE_PROVIDER",
    ROLE_STUDIO="ROLE_STUDIO",
    ROLE_PHOTO="ROLE_PHOTO",
    ROLE_MAKEUP="ROLE_MAKEUP",
    ROLE_MODEL="ROLE_MODEL",

}